### PR TITLE
Wrong glue for scopes

### PR DESCRIPTION
**Pull request by androidbeet**

### CODE REVIEW

**Comment by romanzipp** [comment]
There are two commits from you previous pull requests. Could you open a new one with your a536a57662e29bc0da2b72a186c9f6c9102f39ae commit?

Have you tested the the space separated scopes?
I'm not sure if the `%20` default encoding is handled correctly from twitch as the documentation states `+` https://dev.twitch.tv/docs/authentication/#scopes

**Comment by androidbeet** [comment]
In the documentation it is really indicated on gluing with the help of "+". At the same time, the Twitch API responds with an error on "+" and performs well on " ".

**Comment by androidbeet** [comment]
All ok. Twitch didnt understand `%20`

**Comment by romanzipp** [comment]
Could you test https://github.com/romanzipp/Laravel-Twitch/commit/f3020870a77556960f7721a68a619015e7730c4b? I though, that `http_build_query` would provide percent-escaping, but thats only the case for the default `rawurlencode`. The latest change works for me

**Comment by androidbeet** [comment]
Yeap, " " and "+" work fine. I am use "+". But whit `urldecode`.

**Pull request closed without merging**
